### ISSUE TITLE
Please update the software packages used in the project as soon as possible

### ISSUE THREAD

**Issue by misayalong** [PGYER/pgyer-upload-app-action#1]
GitHub has already issued a warning, informing us to update the relevant api, and our project has also received the warning notice, please developers to update the version as soon as possible.

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/107981091/219267291-9d495e35-6ebc-4d28-91b4-41a2915eaed2.png">

Here is the link address：
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by shishirui** [comment]
Thank you for your feedback, the problem has been fixed.
